flower_shop/Cart/urls.py
from django.urls import path
from . import views
app_name = 'Cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:flower_id>/', views.add_cart, name='add_cart'),
    path('remove/<int:flower_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('delete_cart/<int:flower_id>/', views.delete_cart, name='delete_cart'),
    path('get_cities/', views.get_cities, name='get_cities'),
    path('success/', views.success, name='success'),
    path('order_placed/', views.order_placed, name='order_placed'),

]

flower_shop/flowerApp/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views
app_name = 'flowerApp'

urlpatterns = [
    path('', views.home, name='home'),
    path('flowers/<int:flower_id>/', views.flower_details, name='flower_details'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('categories/', views.category_list, name='categories'),
    path('flowers_list/<slug:category_slug>/', views.flower_list, name='flower_list'),
    path('flower_list/<str:color>/', views.flower_list, name='flower_list_by_color'),

]

flower_shop/flower_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('flowerApp.urls')),
    path('Cart/',include('Cart.urls')),
    path('searchApp/', include('searchApp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                         document_root = settings.MEDIA_ROOT)

flower_shop/searchApp/urls.py
from django.urls import path
from . import views
app_name = 'searchApp'

urlpatterns = [
    path('search/', views.SearchResult, name='search')
]

flower_shop/templates/cart_detail.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">Shopping Cart</h1>
  {% if cart_items %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Product Image</th>
          <th scope="col">Product Name</th>
          <th scope="col">Price</th>
          <th scope="col">Quantity</th>
          <th scope="col">Total</th>
          <th scope="col">Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for item in cart_items %}
          <tr>
            <td><img src="{{ item.flower.image.url }}" alt="{{ item.flower.name }}" width="100px" height="100px"></td>
            <td>{{ item.flower.name }}</td>
            <td>${{ item.flower.price }}</td>
            <td>
              <a href="{% url 'Cart:remove_from_cart' item.flower.id %}">
                <i class="fa fa-minus-circle" aria-hidden="true"></i>
              </a>
              {{ item.quantity }}
              <a href="{% url 'Cart:add_cart' item.flower.id %}">
                <i class="fa fa-plus-circle" aria-hidden="true"></i>
              </a>
            </td>
            <td>${{ item.flower.price }} * {{ item.quantity }}</td>
            <td>
              <a href="{% url 'Cart:delete_cart' item.flower.id %}">
                <i class="fa fa-trash" aria-hidden="true"></i>
              </a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
      <tfoot>
        <tr>
          <td colspan="4">Total:</td>
          <td>${{ total }}</td>
          <td>
            <a href="{% url 'Cart:checkout' %}">
              <button class="btn btn-primary">Checkout</button>
            </a>
          </td>
        </tr>
      </tfoot>
    </table>
  {% else %}
    <p class="text-center">Your cart is empty. <a href="{% url 'flowerApp:categories' %}">Go shopping!</a></p>
  {% endif %}
{% endblock %}

flower_shop/templates/category_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Blossom Garden - Category List{% endblock %}

{% block content %}
<div class="container-fluid">
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container-fluid">
    <div class="row">
      <div class="col" style="font-family:Courier New;">
        <a class="navbar-brand" href="{% url 'flowerApp:categories' %}"><img src="{% static 'img/logo.png' %}" alt="Blossom Garden" height="50">
          <i class="fa fa-home"></i>&nbsp;<b>BLOSSOM GARDEN</b></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto" style="margin-right: 0.0005px;">

            <form class="form-inline my-2 my-lg-0" action="{% url 'searchApp:search' %}" method="get">
              {% csrf_token %}
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-search"></i></button>&nbsp;
            </form>
            <a class="btn btn-primary" href="{% url 'Cart:cart_detail' %}" role="button">&nbsp;<i class="fa fa-shopping-cart"></i></a>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'flowerApp:logout' %}">&nbsp;<i class="fa fa-sign-out"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>


  <!-- Banner -->
  <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <ol class="carousel-indicators">
      <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"></li>
      <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"></li>
      <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active" data-interval="false">
        <img src="{% static 'img/banner 3.png' %}" class="d-block w-100" alt="Banner 1" style="width:100%; height:400px;">
      </div>
      <div class="carousel-item" data-interval="false">
        <img src="{% static 'img/banner 1.png' %}" class="d-block w-100" alt="Banner 2" style="width:100%; height:400px;">
      </div>
      <div class="carousel-item" data-interval="false">
        <img src="{% static 'img/banner 2.png' %}" class="d-block w-100" alt="Banner 3" style="width:100%; height:400px;">
      </div>
    </div>
    <a class="carousel-control-prev" href="carouselExampleIndicators" role="button" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </a>
</div>
<script>
  $(document).ready(function() {
    // Set the interval to move the banner every 1 second
    setInterval(function() {
      // Get the active banner item
      var activeItem = $('#banner .carousel-item.active');

      // Move the banner to the next item
      activeItem.removeClass('active');
      if (activeItem.next('.carousel-item').length) {
        activeItem.next('.carousel-item').addClass('active');
      } else {
        $('#banner .carousel-item').first().addClass('active');
      }
    }, 500);
  });
</script>

<!-- Category List -->
<h3 style="font-family:Garamond; background:#00008B; color:white;padding-top:3px; margin-top:6px;" class="text-center"> See Our Collections</h3>
<div class="row">
  {% for category in categories %}
    <div class="col-md-4" style="font-family:Garamond;">
      <div class="card" style="height:30rem; border: 1px solid #ddd; border-radius: 2px; padding: 3px; margin: 1px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2); transition: 0.3s;">
        <a href="{% url 'flowerApp:flower_list' category.slug %}">
          <img class="card-img-top" src="{{ category.image.url }}" alt="{{ category.name }}" style="width: 100%; height: 399px; object-fit: cover;">
        </a>
          <div class="card-body" style="height:10rem;">
            <h4 class="card-title" style="letter-spacing: 2px; text-align: center;">{{ category.name }} Flowers</h4>
          </div>
      </div>
    </div>
  {% endfor %}
</div>
</div>
{% include 'footer.html' %}
{% endblock %}

flower_shop/templates/checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Checkout</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <div class="container mt-5">
        <div class="card mx-auto" style="max-width: 500px;">
            <div class="card-header">
                <h1 class="text-center">Checkout</h1>
            </div>
            <div class="card-body">
                <form action="" method="POST">
                    {% csrf_token %}
                    <h2>Billing Details</h2>
                    <div class="form-group">
                        <label for="name">Name:</label>
                        <input type="text" class="form-control" id="name" name="name" required>
                    </div>
                    <div class="form-group">
                        <label for="email">Email:</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                                        <div class="form-group">
                        <label for="dob">Date of Birth:</label>
                        <input type="date" class="form-control" id="dob" name="dob" required>
                    </div>
                    <div class="form-group">
                        <label for="age">Age:</label>
                        <input type="number" class="form-control" id="age" name="age" min="1" max="150" required>
                    </div>
                    <div class="form-group">
                        <label for="gender">Gender:</label>
                        <select class="form-control" id="gender" name="gender" required>
                            <option value="">Select Gender</option>
                            <option value="male">Male</option>
                            <option value="female">Female</option>
                            <option value="other">Other</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="phone">Phone Number:</label>
                        <input type="tel" class="form-control" id="phone" name="phone" pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}" required>
                    </div>

                    <div class="form-group">
                        <label for="address">Address:</label>
                        <textarea class="form-control" id="address" name="address" rows="4" cols="50" required></textarea>
                    </div>
  <div class="form-group">
    <form>
      <label for="district-select">District:</label>
      <select id="district-select">
        <option value="">Select a district</option>
        {% for district in districts %}
          <option value="{{ district.id }}">{{ district.name }}</option>
        {% endfor %}
      </select>

      <br>
      <label for="city-select">City:</label>
      <select id="city-select" disabled>
        <option value="">Select a city</option>
      </select>
    </form>
  </div>

  <script>
    $(document).ready(function() {
      $('#district-select').change(function() {
        var districtId = $(this).val();
        if (districtId) {
          $.ajax({
            url: '{% url "Cart:get_cities" %}',
            data: {
              'district_id': districtId
            },
            dataType: 'json',
            success: function(response) {
              $('#city-select').empty().append('<option value="">Select a city</option>');
              $.each(response.cities, function(i, city) {
                $('#city-select').append($('<option>', {
                  value: city.id,
                  text: city.name
                }));
              });
              $('#city-select').prop('disabled', false);
            },
            error: function(response) {
              $('#city-select').empty().append('<option value="">Select a city</option>');
              $('#city-select').prop('disabled', true);
            }
          });
        } else {
          $('#city-select').empty().append('<option value="">Select a city</option>');
          $('#city-select').prop('disabled', true);
        }
      });

      $('#city-select').change(function() {
        var districtName = $('#district-select option:selected').text();
        var cityName = $('#city-select option:selected').text();
      });
    });
  </script>
        <h2>Payment</h2>
<div class="form-group">
    <label for="payment_options">Payment Options:</label><br>
    <input type="checkbox" id="debit_card" name="payment_option" value="debit_card">
    <label for="debit_card">Master Card <i class="fab fa-cc-mastercard"></i></label><br>
    <input type="checkbox" id="credit_card" name="payment_option" value="credit_card">
    <label for="credit_card">Credit Card <i class="fa fa-credit-card" aria-hidden="true"></i></label><br>
    <input type="checkbox" id="rupay" name="payment_option" value="rupay">
    <label for="rupay">PayPal <i class='fab fa-cc-paypal'></i></label><br>
    <input type="checkbox" id="cash_on_delivery" name="payment_option" value="cash_on_delivery">
    <label for="cash_on_delivery">Cash on Delivery <i style="font-size:18px" class="fa">&#xf0d6;</i></label><br>
</div>
<script>
                      const checkboxes = document.querySelectorAll('input[type=checkbox][name=payment_option]');
                      checkboxes.forEach((checkbox) => {
                        checkbox.addEventListener('change', () => {
                          checkboxes.forEach((cb) => {
                            if (cb !== checkbox) {
                              cb.checked = false;
                            }
                          });
                        });
                      });
                    </script>

<div id="card_details">
    <div class="form-group">
        <label for="cardholder">Cardholder's Name:</label>
        <input type="text" class="form-control" id="cardholder" name="cardholder" required>
    </div>
    <div class="form-group">
        <label for="card_number">Card Number:</label>
        <input type="text" class="form-control" id="card_number" name="card_number" required>
    </div>
    <div class="form-group">
        <label for="expiry_date">Expiry Date:</label>
        <input type="date" class="form-control" id="expiry_date" name="expiry_date" required>
    </div>
    <div class="form-group">
        <label for="cvv">CVV:</label>
        <input type="text" class="form-control" id="cvv" name="cvv" required>
    </div>
</div>

<button type="button" class="btn btn-warning btn-block" id="pay_now_button" style="display:none" onclick="window.location.href='{% url 'Cart:success' %}'">Pay Now</button>
<button type="button" class="btn btn-danger btn-block" id="confirm_order_button" style="display:none" onclick="window.location.href='{% url 'Cart:order_placed' %}'">Confirm Order</button>

<script>
  $(document).ready(function() {
    $('#card_details').hide();
    $('#pay_now_button').hide();
    $('#confirm_order_button').hide();

    $('input[name=payment_option]').click(function() {
      if ($('#cash_on_delivery').is(':checked')) {
        $('#card_details').hide();
        $('#pay_now_button').hide();
        $('#confirm_order_button').show();
      } else {
        $('#card_details').show();
        $('#pay_now_button').show();
        $('#confirm_order_button').hide();
      }
    });
  });
</script>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

flower_shop/templates/flower_details.html
{% extends 'base.html' %}

{% block content %}

<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10">
      <div class="card">
        <div class="card-body">
          <h1>{{ flower.name }}</h1>
          <p><b>Description:</b> {{ flower.description }}</p>
          <p><b>Price: ${{ flower.price }}</b></p>
          <div class="mb-3">
            <img src="{{ flower.image.url }}" alt="{{ flower.name }} image" style="width:410px;height:410px;margin-bottom:10px;">
          </div>

          {% if flower.stock == 0 %}
              <p class="card-text text-danger">Out of stock</p>
          {% elif not flower.availability %}
          <span class="badge badge-danger">Unavailable</span>
          {% else %}
          <div class="d-flex justify-content-between">
              <a href="{% url 'Cart:add_cart' flower.id %}" class="btn btn-primary flex-grow-1 w-100 mx-2">Add to cart</a>
              <a href="{% url 'Cart:checkout' %}" class="btn btn-warning flex-grow-1 w-100 mx-2">Buy Now</a>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

flower_shop/templates/flower_list.html
{% extends 'base.html' %}
{% block content %}


<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="filterDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                <ion-icon name="filter-outline" class="me-2"></ion-icon><b>Filter</b>
      </button>
      <ul class="dropdown-menu" aria-labelledby="filterDropdown">
        <li>
          <form method="get">
            <div class="mb-3">
              <label for="color" class="form-label">Color:</label>
              <select name="color" id="color" class="form-select">
                <option value="">--select a color--</option>
                {% for color in colors %}
                  <option value="{{ color }}" {% if selected_color == color %}selected{% endif %}>{{ color }}</option>
                {% endfor %}
              </select>
            </div>
            <div class="mb-3">
              <button type="submit" class="btn btn-primary">Apply</button>
            </div>
          </form>
        </li>
      </ul>
    </div>
  </div>
</nav>

{% if selected_color %}
    <p>Showing <strong>{{ selected_color }}</strong> flowers</p>
{% endif %}

  {% if category %}
    <h1 style="margin-left:15px;">{{ category.name }} Flowers</h1>
  {% else %}
    <h1>All Flowers</h1>
  {% endif %}
  <div class="row">
    {% for flower in flowers %}
      <div class="col-md-3 mb-4">
        <div class="card" style="padding: 0.5px; margin:15px; width: 18rem; height:28rem;">
          <a href="{% url 'flowerApp:flower_details' flower.id %}">
          <img src="{{ flower.image.url }}" class="card-img-top" alt="{{ flower.name }} image" style="width:100%; height:336px;">
          </a>
            <div class="card-body text-center">
            <h5 class="card-title" style="font-family: 'Courier New', monospace;letter-spacing: 2px;">{{ flower.name }}</h5>
            <p class="card-text"><b>Price:{{ flower.price }}$</b></p>
            {% if flower.stock == 0 %}
              <p class="card-text text-danger">Out of stock</p>
            {% elif not flower.availability %}
              <span class="badge badge-danger">Unavailable</span>
            {% endif %}
          </div>
        </div>
      </div>
    {% empty %}
      <div class="col">
        <p>No flowers found.</p>
      </div>
    {% endfor %}
  </div>
{% endblock %}

flower_shop/templates/footer.html
<footer class="fixed-footer" style="position: fixed; width: 100%;">
  <div class="container">
    <div class="row mx-auto" style="text-align:center;">
      <div class="col-md-12">
        <p>&copy; 2023 Blossom Flower Shop. All rights reserved.</p>
      </div>
    </div>
  </div>
</footer>

flower_shop/templates/homePage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    body {
        background-image: url("{% static 'img/background.jpg' %}");
        background-repeat: no-repeat;
        background-size: 2000px;
    }
    .navbar {
    background-color: gray; /* Set the background color of the navbar */
    padding: 1px 5px; /* Add some padding to the navbar */
    }
</style>


<!-- Navbar -->
<nav class="navbar navbar-expand-lg" style="height:60px;">
  <a class="navbar-brand" href="#"><img src="{% static 'img/logo.png' %}" alt="logo" style="width:60px;height:60px;"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <p style="color:white;">BLOSSOM<span class="sr-only"></span></p>
    <ul class="navbar-nav ml-auto" style="margin-right: 100px;">
      <li class="nav-item">
        <button class="btn btn-success mr-2" type="button" onclick="location.href='{% url 'flowerApp:login' %}'">Login</button>
      </li>
      <li class="nav-item">
        <button class="btn btn-danger" type="button" onclick="location.href='{% url 'flowerApp:register' %}'">Register</button>
      </li>
      <div class="dropdown ml-2">
      <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Branches
      </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thiruvananthapuram">Thiruvananthapuram</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kollam">Kollam</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Pathanamthitta">Pathanamthitta</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Alappuzha">Alappuzha</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kottayam">Kottayam</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Idukki">Idukki</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Ernakulam">Ernakulam</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thrissur">Thrissur</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Palakkad">Palakkad</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Malappuram">Malappuaram</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kozhikode">Kozhikode</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Wayand">Wayanad</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kannur">kannur</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kasargod">Kasargod</a>
        </div>
      </div>
    </ul>
  </div>
</nav>

<footer style="position: fixed; bottom: 0; width: 100%; color:">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h3>Contact Us</h3>
        <ul>
          <li>1234 Blossom Street</li>
          <li>Springfield, USA</li>
          <li>Phone: (123) 456-7890</li>
          <li>Email: info@blossomflowerapp.com</li>
        </ul>
      </div>
      <div class="col-md-4">
        <h3>About Us</h3>
        <p>Blossom Flower is a mobile app that makes it easy to find and order beautiful, fresh flowers for any occasion.</p>
      </div>
      <div class="col-md-4">
        <h3>Follow Us</h3>
        <ul class="social-media">
          <li><a href="#"><i class="fa fa-facebook" style="color:blue"> <b>facebook.com/blossom.flowers.27/</b></i></a></li>
          <li><a href="#"><i class="fa fa-twitter"></i> <b>@BlossomFlowerShop</b></a></li>
          <li><a href="#"><i class="fa fa-instagram" style="color:red"> <b style="color:black;">@flowerblossomshop</b></i></a></li>
          <li><a href="#"><i class="fa fa-pinterest" style="color:red"> <b style="color:black;">@flowerblossomshop</b></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>
{% endblock %}

flower_shop/templates/order_placed.html
{% extends 'base.html' %}

{% block content %}
  <div class="contain-fluid" style="margin-top:210px;margin-left:540px;">
    <h2 style="color:black;margin-left:24px;">Congratulations</h2>
    <h5 style="color:red;margin-left:10px;"> <b>Your Order Has Been Placed</b></h5>
    <button class="btn btn-primary" style="margin-left:100px;"><a href="{% url 'flowerApp:logout' %}"><b style="color:white;">Logout</b></a></button>
      <br><br>
    <p style="margin-left:-30px;">Keep Shop With Us <a href="{% url 'flowerApp:categories' %}">Click here</a> Go back to Shopping</p>
  </div>

{% endblock %}

flower_shop/templates/search.html
{% extends 'base.html' %}

{% block content %}
<div>
  <p class="text-center" style="padding-top:20px;">You have searched for: <b>"{{query}}"</b></p>
</div>
<div class="container">
  <div class="row mx-auto">
    {% if flowers %}
    {% for flower in flowers %}
    <div class="col-9 col-sm-12 col-md-4 xol-lg-4">
      <div class="card text-center" style="padding: 0.5px; margin:15px; width: 18rem;">
        <div class="card">
          <a href="{{flower.get_url}}">
          <img src="{{ flower.image.url }}" class="card-img-top" alt="{{ flower.name }} image" style="width:100%; height:300px;"></a>
            <div class="card-body">
            <h5 class="card-title">{{ flower.name }}</h5>
            <p class="card-text"><b>Price:{{ flower.price }}$</b></p>
            {% if flower.stock == 0 %}
              <p class="card-text text-danger">Out of stock</p>
            {% elif not flower.availability %}
              <span class="badge badge-danger">Unavailable</span>
            {% else %}
            <div class="d-flex justify-content-between">
              <a href="{% url 'Cart:add_cart' flower.id %}" class="btn btn-primary flex-grow-1 w-100 mx-2">Add to cart</a>
              <a href="{% url 'Cart:checkout' %}" class="btn btn-warning flex-grow-1 w-100 mx-2">Buy Now</a>
            </div>
              {% endif %}
        </div>
      </div>
    </div>
    </div>
    {% endfor %}
    {% else %}
    <div class="row mx-auto">
      <p class="text-center" style="padding-top:20px;">0 results found</p>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

flower_shop/templates/success.html
{% extends 'base.html' %}
{% block content %}
  <div class="contain-fluid" style="margin-top:210px;margin-left:540px;">
    <h1 style="color:light blue;">Congratulations</h1>
    <h4 style="color:green;margin-left:27px;"><b>Payment successful</b></h4> <h5 style="color:red;margin-left:6px;"> <b>Your Order Has Been Placed</b></h5>
    <button class="btn btn-primary" style="margin-left:100px;"><a href="{% url 'flowerApp:logout' %}"><b style="color:white;">Logout</b></a></button>
      <br><br>
    <p style="margin-left:-30px;">Keep Shop With Us <a href="{% url 'flowerApp:categories' %}">Click here</a> Go back to Shopping</p>
  </div>
{% endblock %}